### ISSUE TITLE
Changing version does not bust cache

### ISSUE THREAD

**Issue by fphilipe** [rails/sprockets-rails#240]
This only happens in combination with sprockets v3 (tested with 3.0.1 and 3.0.2). Changing the `version` config does not result in different digests for the individual assets.

How to reproduce:

```
gem install rails
rails new foobar
cd foobar
rake assets:precompile
ls public/assets > assets1.txt
tr "'1.0'" "'2.0'" < config/initializers/assets.rb | tee config/initializers/assets.rb
rake assets:precompile
ls public/assets > assets2.txt
[[ -z "$(diff assets*.txt)" ]] && echo "no diff" || echo "diff"
```

Notice how the file names are the same between the two `version` configs.

Adding `gem 'sprockets', '< 3'` to the Gemfile and repeating the steps above results in different file names, as expected.

**Comment by josh** [comment]
> Changing the version config does not result in different digests for the individual assets.

Bumping the version will rev the cache but will not result in a different digest. Digests are only based on the SHA256 of the file.

See the https://github.com/rails/sprockets/blob/master/CHANGELOG.md

**Comment by fphilipe** [comment]
So how can I bust the cache if the file name is still the same? The client will just use the file from a previous request. Wasn't that the whole point of the version config, to change all asset file names and thus bust the cache?

**Comment by Erol** [comment]
Any updates on this? My workaround in the meantime was to include versions on the asset sources, since our production apps usually only have a couple of precompiled assets - mainly application.js & application.css.

**Comment by matthewd** [comment]
@josh can you expand on the reasoning behind https://github.com/rails/sprockets/commit/07e5e29e2ec93c70c6783c4fc6f3c34f1a3442a8? This seems like a Bad Thing to me.

**Comment by josh** [comment]
It'd be nice if the builtin rails `?123` cache busters could simply be appended to these urls if you wanted to rev caches for CDN changes.

**Comment by josh** [comment]
The main reason for this change was to separate the filename itself from any caching logic. This allowed for extensions like coffeescript to rev just its cache when it was upgraded so the user never has to touch any `version` manually. Since the file fingerprint is a pure SHA256, its not affected unless the content changes. Upgrading CoffeeScript shouldn't force a cache invalidation of every other asset the site hosts. This made it much easier to roll out changes to sprockets and any subdependencies.

**Comment by wezm** [comment]
I've been pulling my hair out for a couple of hours over this. I have assets cached in a CDN with incorrect `Access-Control-Allow-Origin` headers so I need to invalidate them all. As mentioned here changing the version doesn't alter the filename so the CDN continues to serve the stale responses.

The change introduced in Sprockets 3 appears to leave no way to expire all assets, which is contrary to the expected behaviour and the comment included in new rails projects:

```ruby
# Version of your assets, change this if you want to expire all your assets.
Rails.application.config.assets.version = '1.0'
```

**Comment by ptrikutam** [comment]
I'm having the same issue here -- anyone have a workaround?

**Comment by wezm** [comment]
`gem 'sprockets', '< 3.0.0'` was my workaround.

**Comment by ptrikutam** [comment]
Gotcha. Thanks, I'll try that.

**Comment by jordan-brough** [comment]
This caused us some pain today as well.

FYI, depending on how your CDN is set up, this workaround may do the trick for you:

```ruby
Rails.application.config.assets.prefix = "/assets/v1" # change the "vX" to bust asset caches on all your assets
```

**Comment by jordan-brough** [comment]
> Bumping the version will rev the cache

@josh was does "rev the cache" mean?  Do you mean it will force `assets:precompile` to regenerate the assets, even though they end up with the same digest (and filename) if they haven't changed?

**Comment by rafaelfranca** [comment]
@jordan-brough yes.

**Comment by jordan-brough** [comment]
@josh @rafaelfranca @matthewd -- Cache-busting for CDNs seems like a relatively common need and `config.assets.version` used to work for that and now it doesn't.  The [current wording](https://github.com/rails/rails/blob/v4.2.5/railties/lib/rails/generators/rails/app/templates/config/initializers/assets.rb.tt#L3) is also a little confusing in that way.  Can we do something to improve the messaging and/or behavior?

A few ideas:

1) Restore the old behavior.

Ensure that changing `config.assets.version` changes the filename for every asset.  This doesn't seem reasonable at this point does it?  (Personally I like the new behavior better and it sounds like @josh does too).

2) Append a cache-buster query string if `config.assets.version` is set.

This doesn't seem like a good idea for the reasons outlined [in the rails guides](http://guides.rubyonrails.org/v4.2/asset_pipeline.html#what-is-fingerprinting-and-why-should-i-care-questionmark).

3) Improve the messaging in initializers/assets.rb and offer a method for CDN cache-busting.

e.g. something like [this](https://gist.github.com/jordan-brough/581f17ff366d7b9a5ca8).

Any thoughts?  I'll be happy to make a pull request if one of those or something else seems reasonable.

**Comment by matthewd** [comment]
@jordan-brough we're doing option 1. The very point of `config.assets.version` is to force a change to every asset.

Can you elaborate on why you find the current behaviour useful? If you want a one-off cache flush, it seems simpler to just use the appropriate rake task. :confused:

**Comment by jordan-brough** [comment]
> The very point of config.assets.version is to force a change to every asset

I don't have the context on what this setting was originally intended for. I've only recently started using it and there's not much documentation around it that I could find. I think some of @josh's earlier comments confused me perhaps.

> Can you elaborate on why you find the current behaviour useful?

I like the simplicity of the filename only depending on the contents of the file.  Separating the concern of cache-busting for CDN-like purposes into something else seems attractive to me.  E.g. by putting it into the path instead of the filename.

Personally I'd be happy with either option 1 or option 3.  But I did notice that this has been broken for 6 months now so I was thinking perhaps option 3 would be easier at this point if option 1 was now contrary to 'the sprockets way'.

**Comment by Sija** [comment]
:+1: for option 1 — changing `config.assets.version` doesn't happen that often, but when it does, busting cache is its main purpose.

Option 2 is bad practice (as outlined in Rails' guide) and messing with `config.assets.prefix` seems like a hack.

**Comment by MattFenelon** [comment]
Could I get an update on this issue?

**Comment by MatayoshiMariano** [comment]
Same here, what is the status of this issue?

**Comment by nfm** [comment]
We just ran into this issue too, and were expecting incrementing the `config.assets.version` to force a recompile with new asset fingerprints. Same use case - cache busting on our CDN due to bad headers.

My workaround *would* be to manually force a new fingerprint by changing the contents of the file, but some of the top-level files are being sourced from gems, so that won't work.

**Comment by MatayoshiMariano** [comment]
@nfm until the [PR](https://github.com/sellect/sprockets/pull/1) is approved I have downgraded the version of sprockets. `gem 'sprockets', '< 3.0.0'`

**Comment by Erol** [comment]
I'm also interested with the outcome of this issue. Is there an update?

**Comment by lime** [comment]
Would the maintainers be open to a config option that would have the cache version affect the digest? Essentially an opt-in to use the old behaviour.

```ruby
Rails.application.configure do
  config.assets.version = '1.0'
  config.assets.versioned_digests = true
end
```

**Comment by rafaelfranca** [comment]
@lime yes. It doesn't need to be opt-in, we are fine to restore the previous behavior.

**Comment by lime** [comment]
Thanks for that clarification, @rafaelfranca!

**Comment by ayb** [comment]
+1 

Would love to see this resolved at some point.

**Comment by btsai** [comment]
@rafaelfranca you say "we are fine to restore the previous behavior.", but is this in the pipeline?

thank you!

**Comment by matthewd** [comment]
@btsai no, I don't believe anyone has made a PR implementing the agreed change.

**Comment by jasdeepsingh** [comment]
got badly bitten by this issue this evening and wasted a few hours like others already have. Wondering if a fix could be shipped soon?

@kilgore5 also had a look at your PR here: https://github.com/sellect/sprockets/pull/1 looks like you intended to open this PR in https://github.com/rails/sprockets ?

**Comment by matthewkrom** [comment]
+1 If we use a Procfile for config.assets.host, and we need to change all the asset hashed filenames quickly, config.assets.version is the way to go.  Are you looking for someone to make the pull request, or do you have folks to do it?

**Comment by kilgore5** [comment]
@jasdeepsingh based on conversation above I wasn't sure if the behavior was desired, so I decided to fork for the time being (which turned into a monkey-patch instead), rather than PR to rails/sprockets. 

I'm glad to see the behavior being restored in https://github.com/rails/sprockets/pull/404 mentioned above.

**Comment by fphilipe** [comment]
I guess this issue can be closed with the merge of rails/sprockets#404. /cc @rafaelfranca

**Comment by rafaelfranca** [comment]
Thanks!

**Comment by feliperaul** [comment]
Also lost +1 hour on this today. 

Just want to point that I'm on Rails 5.2, which defaults to sprockets 3.7.1, and this bug still occurs.

As far as I could see, there's an open pull-request https://github.com/rails/sprockets/pull/478 to backport this to sprockets 3.7, since the merge mentioned in https://github.com/rails/sprockets/pull/404 was for version 4 only, which Rails 5.2. still doesn't use. 

Considering a brand new Rails 5.2 app has the following line in `config/assets.rb`:
`# Version of your assets, change this if you want to expire all your assets.`

And changing that version number does nothing, I consider this to be an open bug and maybe this could be reopened. 

@rafaelfranca could you please reconsider?
