### ISSUE TITLE
AssetAliasUsed should not affect Sass Helpers

### ISSUE THREAD

**Issue by josh** [rails/sprockets-rails#247]
AssetAliasUsed should only be raised from ActionView helpers, not within static assets themselves.

I think this is only a probably with the 2.x backport. 3.x already behaves as intended.

https://github.com/rails/sprockets-rails/issues/246
https://github.com/github/octicons/issues/50

/cc @rafaelfranca

**Comment by rafaelfranca** [comment]
The reason is that we include the [helpers inside the assets context](https://github.com/rails/sprockets-rails/blob/2.x/lib/sprockets/railtie.rb#L30), so we would have to do something like https://github.com/rails/sprockets-rails/commit/32a58f549de09528df787867e473dd7dc3a443f4

**Comment by josh** [comment]
Yeah, for 2.x, I think we just want to do a quick feature check *somehow* and only apply it to AV. Maybe see if we're `is_a?(ActionView::Base)`?

**Comment by rmosolgo** [comment]
Hey there, just wanted to double-check that I'm experiencing the desired effect here. 

## react-rails setup 

In `react-rails`, app config specifies either `production` or `development`, based on that, we add a path to `app.config.assets.paths`, roughly speaking:

```ruby
# add directory to asset pipeline, 
# based on the app config
app.config.assets.paths << root_path.join('lib/assets/react-source/').join(directory).to_s
```

([full src](https://github.com/reactjs/react-rails/blob/master/lib/react/rails/railtie.rb#L45-L49))

We do this so that the app only needs `//= react`, then, each environment gets its version of React.js (the development version has nice error messages, the production version has none). 

## error 

However, we get an `AssetAliasUsed` from the `javascript_include_tag` helper:

![image](https://cloud.githubusercontent.com/assets/2231765/7687233/8fe427e4-fd50-11e4-978e-f38b116e53d2.png)

Sure enough, these don't match: 

![image](https://cloud.githubusercontent.com/assets/2231765/7687214/69c605fa-fd50-11e4-870b-00b8114daa7d.png)

Interestingly, if I upgrade to Sprockets 3 + sprockets-rails 2.3.1, I don't get this error (which is fine for me, but not fine for many other `react-rails` users...).

Is this the expected outcome? Are we misusing the asset pipeline? Anything else I can do to diagnose or address this?

We're really hoping to support an API where `//= require react` can provide different versions of the file based on environment configs. Previously we copied JS files into local directories, but that had its own issues!

Thanks!

**Comment by aripollak** [comment]
It seems like this gem now needs a dependency on sprockets >= 3.0?

**Comment by rafaelfranca** [comment]
The master branch yes, the released branch no. It works with both version.

**Comment by rmosolgo** [comment]
Ok, can you help me understand that error? I don't know why our use of that `Environment` was unsafe (or how to rework our process)

**Comment by rafaelfranca** [comment]
@rmosolgo the check is gone at master branch, so I think we need to revert it in 2.x and release 2.3.2. @josh confirm?

**Comment by rmosolgo** [comment]
Any word on 2.3.2 ? 

I'm hoping to get out a new version of `react-rails` but I don't want to publish it while it's incompatible with the latest `sprockets-rails` 2.x!

I can try to help, but I don't quite understand what needs to be done. Should I just remove the whole check & error?

**Comment by rafaelfranca** [comment]
@rmosolgo could you open a new issue so we can keep track of this and not forget to release?

**Comment by rmosolgo** [comment]
happy to!
