### ISSUE TITLE
Precompiling assets modifies the manifest file between environments

### ISSUE THREAD

**Issue by Jaco-Pretorius** [rails/sprockets-rails#264]
We are trying to version our precompiled assets in an effort to speed up our deploys.  (Currently 90+% of our deploys are spent precompiling assets)

This is the pattern we're seeing:

Dev 1 -> Precompile assets and check into git
Dev 1 -> Precompile assets = no local changes (in git)
Dev 2 -> Checkout and precompile assets = modifies the manifest file (even though no new files are generated or modified)

I suspect this is related to backups, since the modified manifest file seems to contain 2 copies of all the assets.  Unfortunately there doesn't currently seem to be any way of switching off backups (2.12.4).

Are we trying an unsupported use case?  Is there something I'm missing?  I assumed that since the digests are the same across environments nothing should change during precompilation, but that doesn't seem to be the case.

**Comment by mgodwin** [comment]
The checksums generated by this task are actually housed in the https://github.com/rails/sprockets project - class in question is the `Environment` class.  It gets a bit hairy going through all the code in there.  Also worth discussing is the version of sprockets being used, because I know the maintainer of sprockets has changed how checksums are generated in recent versions (3+), so that could potentially fix this problem going forward?

Also in past digging I found that the digest/checksum generated included the OS information in it, but that may have also been removed.

Worth noting, I think you can get what digest is generated during precompilation by running the following in a rails console:

```
irb(main):006:0> Rails.application.assets.digest
=> #<Digest::MD5: 361c512b9086418778df946c0d278f91>
```

And note that when running it with `RAILS_ENV=production`

```
irb(main):001:0> Rails.application.assets.digest
=> #<Digest::MD5: 8d77f8cef56555463ecffc07c5f39ba8>
```

My version of sprockets is 2.11.0.

**Comment by Jaco-Pretorius** [comment]
@mgodwin Thanks for shedding a bit more light.  I have spent quite a bit of time in the sprockets project - and it really is very difficult to debug.  I did put my version number up there (2.12.4), but I haven't tried it on version 3+.

There was a very long thread about the OS information 2 years ago (which I read through), but AFAIK that has been resolved.

**Comment by mgodwin** [comment]
For the life of me I can't figure out where the file fingerprint is generated in the sprockets source.  Is it I assume it has to do with `PrecompiledAsset` but I can't track it down.  I also can't get the digest to differ between mine and a co-workers machine inside the rails console.

**Comment by rafaelfranca** [comment]
Could you check with sprockets 3?

**Comment by srisa** [comment]
I have a similar issue. I have deployed my app to staging and production environments. The MD5 fingerprints generated for assets are totally different in both the environments. 

**Local Production:**
```
ss1-b910a72898c216b3112637a9d89e9b25.png
```

**In staging**
```
ss1-0a923ec016a416e76a914c6ce389ecde.png
```

**In Production**
```
ss1-87463b7a6c4b3842d9c685bafeb0365d.png
```
This is very confusing. Why would fingerprint of an image change across environments?
I am using Rails 4.1.12 with Sprockets 2.12.4 and Sprockets-rails 2.3.2. The application is deployed using Capistrano 3.

**Comment by rafaelfranca** [comment]
Could you check with sprockets 3? Sprockets 2 is being deprecated.

**Comment by srisa** [comment]
Upgrading to Sprockets 3 fixed the issue. Thanks!

**Comment by srisa** [comment]
Upgraded to Sprockets 3.  fingerprints of JS, images,fonts are consistently generated, but the problem persists with css files. Three different files generated in three different boxes.

```
application-b5e6dc1a51a4c9ffd794e49fabd638e6101254809f929ad7dc02f4c68c70d73a.css
application-fdd321834a64f3dc2dc4bddad3b437cae71f68f511f128d553accafdf2f6ae17.css
application-0cd79727dc358ce1e4a36856d05f725f12494bd24ab9f6540ef110ada15dbcd5.css

**Comment by srisa** [comment]
**Update:** Updating to Sprockets 3 fixed the issue. Ignore my comment above. I am using CDN to serve my assets. The CDN host name is different for each environment. That explains the different MD5 fingerprints for different environments.

**Comment by rafaelfranca** [comment]
Thank you for confirming

**Comment by Jaco-Pretorius** [comment]
@rafaelfranca @srisa I guess I am missing something, but that still sounds like a bug to me - why does a different host name produce a different fingerprint?  The digest doesn't change, so why is the fingerprint different?

**Comment by rafaelfranca** [comment]
See https://github.com/rails/sprockets-rails/blob/v2.3.3/lib/sprockets/railtie.rb#L95.

The reason is, the assets host may be included in the assets so if we didn't change the version it will point to the wrong host.

**Comment by srisa** [comment]
In my case,in one of my css files, I have something like this.

```
.filler {
    background- image url(asset-path("marker.png"));
 }
```
When it is compiled, It will generate different paths using different hosts in each environment i.e., In staging it will be
 
```
 https://xxxxxxxxx.cloudfront.net/assets/marker-xxx.png
```
In production it will be(with a different CDN host),

``` 
https://yyyyyyy.cloudfront.net/assets/market-xxx.png

```

Essentially, the generated applicaton.css  is different as the generated urls are different. Hence the different MD5 fingerprint.

**Comment by Jaco-Pretorius** [comment]
@srisa Ah thank you - that makes it perfectly clear

**Comment by voltechs** [comment]
Why is `asset-path` generating a URL? `asset-url` should be reserved for that. `asset-path` should only do the path part. We have three environments with non-changing assets _except_ for the hostname in the URL, so we opt to use the `asset-path`. Unfortunately `asset-path` is producing a URL, and since our asset_host changes per environment, the asset only works in the environment it was compiled in. 

We've added a proc to all our environments which detects a "build" flag (we're using Docker) and sets the asset_host to `nil` if that's the case. Of course, this works, and doesn't require us to place this in all environments, which means we could create it's own dedicated `build` or `docker` environment with an `asset_host` of `nil`, but my original question/critique remains: Why does `asset-path` return a URL, particularly when we have `asset-url` for that?
