### ISSUE TITLE
SRI doesn't seem to be working

### ISSUE THREAD

**Issue by shaneog** [rails/sprockets-rails#280]
I'm trying to enable SRI (Subresource Integrity) but it does not seem to be working. 

Are there any other steps to take to make it work other than adding `integrity: true` to the `javascript_include_tag` helper?

The manifest file contains the integrity hashes but the helper is not outputting them to the page.

I've put an minimal example Rails app here, to show the problem: https://github.com/shaneog/sprockets-test

**Comment by rafaelfranca** [comment]
Is the page being requested with ssl?

**Comment by shaneog** [comment]
:flushed: It is not, not in my local environment. Is SSL required for the helper to output the integrity hash?

**Comment by rafaelfranca** [comment]
Yes https://github.com/rails/sprockets-rails/blob/master/lib/sprockets/rails/helper.rb#L175-L176

**Comment by shaneog** [comment]
Thanks

**Comment by nickrivadeneira** [comment]
Since the code has changed since rafaelfranca posted that link and the line numbers are now off, here's the code from [that point in time](https://github.com/rails/sprockets-rails/blob/a955c164d7e55bc133d118acba69db1ae5a4e357/lib/sprockets/rails/helper.rb#L175-L176), and here it is at the [time of this writing](https://github.com/rails/sprockets-rails/blob/6fa795ae1d7e1ad1b175ba8e8bb2093f3d868412/lib/sprockets/rails/helper.rb#L209-L210).
