### ISSUE TITLE
Still using version 2.3.3 to fix the bug Sprockets::Rails::Helper::AssetNotPrecompiled

### ISSUE THREAD

**Issue by willingchangthernguyen** [rails/sprockets-rails#349]
I am using requirejs-rails newest version 1.0.0 and sprockets-rails 3.0.4
it shows the error : 
Sprockets::Rails::Helper::AssetNotPrecompiled in Home#index
Asset was not declared to be precompiled in production.
Add `Rails.application.config.assets.precompile += %w( footer/footer-app.js )` to `config/initializers/assets.rb` and restart your server
    %title 
    = requirejs_include_tag "application"

**Comment by rafaelfranca** [comment]
This is your application or requirejs-rails issue. You need to declare all assets that needs to be included in the precompile list.

If this specific file should not needed to be put in the precompile list because some thing defined by requirejs-rails so it is an issue in requirejs-rails.

If this assets should be compiled and served in production so you should put ir in the precompile list in your application.

**Comment by willingchangthernguyen** [comment]
Thank for your support
I am asking them requirejs-rails
But I think I am using many versions of requirejs-rails ,still keeping the errors.
I will say you when they can answer the issue

**Comment by rafaelfranca** [comment]
Maybe because there is no requirejs-rails version that support sprockets-rails 3. Please let me know when they answer the issue.
