### ISSUE TITLE
Question: Why is Rails.env part a resolving dependency?

### ISSUE THREAD

**Issue by nambrot** [rails/sprockets-rails#387]
I'm currently trying to figure out why Rails.env needs to be a resolving dependency for sprockets fingerprints? As far as I can see (and imo according to the docs), fingerprinting based upon the file contents should be sufficient? What i'm trying to get to is to run `assets:precompile` independent of the environment im running it in

**Comment by jeremy** [comment]
That captures possibly-different config in each env.

If we capture e.g. coffeescript/uglifier/etc config as fingerprint deps, then perhaps we could remove the Rails.env dep.

**Comment by nambrot** [comment]
Got it. So the file-content based fingerprint is not based upon the final compiled file, but the original file? It would be nice if there is an escape hatch somewhere. In our case, we use docker to build our apps, but since fingerprinting is dependent on the rails environment, we end up needing one dockerfile per environment. I can't even find an easy to to monkeypatch this either

**Comment by jeremy** [comment]
Yes, fingerprints are based on inputs, not outputs. That makes incremental compilation and intermediate caching possible. Otherwise we'd need to compile * in all cases.

**Comment by jeremy** [comment]
My bad: the assets' digest paths (foo-<digest>.js) are based on a digest of the content of the asset itself. Thanks @rafaelfranca :)

The Rails.env (and Sprockets version and asset paths and …) are incorporated as dependencies for asset compilation and caching.

Theoretically, this means that if you have identical asset compilation config, you should get identical asset contents and, hence, identical asset digest paths in any environment.

**Comment by nambrot** [comment]
Thanks for the clarification @jeremy . So are you saying that `digest of the content of the asset itself` still refers to the original file, correct?

We have just the vanilla asset pipeline config, but we definitely get different digest paths per environment. When I out-comment the dependency on the Rails.env then I do receive identical digest paths. What am I missing here?

**Comment by rafaelfranca** [comment]
It is digest of the content of the generated file. If you are using vanilla asset pipeline config in development assets are not minified but in production they are so the content of the generated files differ between those environments. Make sure all configs are the same that the digests will be the same.

**Comment by mike-stewart** [comment]
I'm running into this same problem on Sprockets 2.x. I realize this is an old version, so if the behaviour has changed in 3.x please let me know.

I am running asset precompile in a Docker build, and looking to re-use this docker image across multiple Rails environments that use the same asset configuration and dependencies (actually identical). However, it seems that changing the Rails.env string will change the digest value in the filename.

It looks like the Rails.env string is used to invalidate the cache here in 2.x: https://github.com/rails/sprockets-rails/blob/2.x/lib/sprockets/railtie.rb#L91-L97

And it's added as a dependency in 3.x here: https://github.com/rails/sprockets-rails/blob/master/lib/sprockets/railtie.rb#L146

Is there some way to disable this behaviour in 2.x, so that the Rails.env string is not a dependency? Or does upgrading to 3.x solve this problem?

**Comment by rafaelfranca** [comment]
Upgrading to 3.x fix the problem.
