### ISSUE TITLE
Rails.application.assets returning nil in production

### ISSUE THREAD

**Issue by anson2590** [rails/sprockets-rails#425]
Im using Rails 5.1.5 and sprockets-rails 3.2, when i try to run my application in production mode image file (default.png) its not fetching it from public folder though the file is present in public folder.

code: 
     open(Rails.application.assets[File.join(default.png)].filename) { |f| f.read }

error im getting in production:
     undefined method `[]' for nil:NilClass

In development mode it works, can anyone please help me to fix this issue.

**Comment by rafaelfranca** [comment]
It is by design. In production assets are not compiled on the fly, so `Rails.application.assets` is `nil`. When compilation is enabled `Rails.application.assets[File.join(default.png)].filename` doesn't read the file from the public folder, it compiles the file again. This is the reason why we set it to `nil`, so people don't think they are reading the file from the disk when in reality they are compiling the file gain.
