### ISSUE TITLE
Incorrect relative URL in css

### ISSUE THREAD

**Issue by chuchiperriman** [rails/sprockets-rails#478]
We have updated sprockets-rails to 3.3.0 and now relative urls are wrong. With his line in css:

`src: url(./fontawesome/fa-brands-400.eot);`

the url is transformed to:

`src: url(/./fontawesome/fa-brands-400.eot);`

The first slash is incorrect because we have the font files in a path relative to the css, not in the root

**Comment by tvdeyen** [comment]
Happening for us as well. The weird thing is that for us it is the other way round. Without `./` the url is considered absolute instead of relative. Changing it to `./` helped. I assume it is because you are not using quotes, while we are.

See https://github.com/AlchemyCMS/alchemy_cms/commit/c6e3cf2a2cac020f1d8a955b6a1ef06689f197f2

**Comment by rafaelfranca** [comment]
The new url processor will change relative paths to absolute paths, but at least the absolute paths should be correct. @jcoyne can you take a look?

**Comment by jcoyne** [comment]
Yes, I'll have a look.
