### ISSUE TITLE
asset_path, javascript_path etc helpers not working in production on Rails 4 RC1

### ISSUE THREAD

**Issue by mrbrdo** [rails/sprockets-rails#66]
I've been using Rails 4.0.0.rc1, and the assets helpers are not working correctly.
I've tried many, like asset_path, javascript_path, compute_asset_path, asset_digest_path etc. all return the paths like '...asset.ext' - without the digest, which I am using. digest_assets is also nil and assets_manifest is also nil, but I am using all of these. I don't have compile enabled in production (as per default). I want to get the path of an asset in production.
The web app itself works fine, i.e. the assets are displayed and used correctly by Rails itself, but I need to get the path in my code, and this is not working for me.

Thanks!

**Comment by aguynamedben** [comment]
Thanks for your hard work on this gem. I'm trying to understand something about the design...

I also need to get the full URL of a production digest asset for use outside of a Rails view or Rails mailer. Use case: I'm working with an external API (Sendwithus, to send, track, and A/B test email marketing), and I want to get various production CDN paths for our logo and some other images.

In Rails 3.2 I did this to get the full digest path of an image...

```ruby
module AssetHelper
  # Because Rails 3 doesn't have image_url.
  # http://stackoverflow.com/a/12483228/3516664
  def get_digest_file(source)
    if Rails.application.config.assets.digests.present?
      return ActionController::Base.asset_host + "/assets/" + Rails.application.config.assets.digests[source.to_s.downcase]
    else
      return ActionController::Base.helpers.asset_path(source.to_s.downcase)
    end
  end
end
```

Now, after upgrading to Rails 4.0.x, `Rails.application.config.assets.digests` is nil due to design changes in Sprockets' internals.

I noticed from the Sprockets docs that now all asset digest paths I seek are written to public/assets/manifest-<hash>.json. Am I expected to open that file myself to get asset digest paths? Or is there an accessor/method/helper to get this?

I don't understand the design here. Why is it so difficult to get the production URL/path of a file that Sprockets is managing? Why does asset_digest_path only run from the view level? Is that by design? Without being able to easily re-generate the digest URLs outside of a view, SASS/LESS, or ActionMailer, it's like my assets are getting locked in a box unless I conform to very narrow use cases. From a developer's perspective, it makes the beauty of Sprockets digest management completely unportable and reusable.

Here is a related open issue where somebody wants to get digest URL for use in JavaScript: https://github.com/rails/sprockets-rails/issues/267

Thanks again very much for your time, and any guidance or thoughts you could provide. I feel like maybe I'm just missing something, but I'm not sure.

**Comment by aguynamedben** [comment]
I think I got it working like this...

```ruby
module AssetHelper
  # Somehow, you can't use Rails or Sprockets helpers directly if you're not in a view. You have to call them from the context of a Controller.

  def digest_file_full_url(source)
    ActionController::Base.asset_host + ActionController::Base.helpers.asset_path(source)
  end
end
```

From looking at the [ActionView::Helpers::AssetUrlHelper](http://api.rubyonrails.org/classes/ActionView/Helpers/AssetUrlHelper.html) docs, I'm still not sure why...

```ruby
include ActionView::Helpers::AssetUrlHelper
asset_url(source)
```

...doesn't get the full URL, even when `Rails.application.config.action_controller.asset_host` is set to my CDN, or even if I call `asset_url(source, host: "http://blah.com").

Hopefully this is helpful to somebody down the road. Very confusing.

**Comment by ericraio** [comment]
Here's my implementation that I started using if it's helpful

```ruby
# frozen_string_literal: true

module AssetUrlHelper
  delegate :image_url, :asset_url, to: :asset_helpers

  def asset_helpers
    ActionController::Base.helpers
  end
end
```
